# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path3/path4/demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='path3/path4/demo.proto',
  package='path3',
  syntax='proto3',
  serialized_pb=_b('\n\x16path3/path4/demo.proto\x12\x05path3\"\x1a\n\nMessageOne\x12\x0c\n\x04name\x18\x01 \x01(\tBQ\n\x1d\x63om.github.biolee.path3.path4Z0github.com/biolee/grpc_starter/path3/path4;path4b\x06proto3')
)




_MESSAGEONE = _descriptor.Descriptor(
  name='MessageOne',
  full_name='path3.MessageOne',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='path3.MessageOne.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=33,
  serialized_end=59,
)

DESCRIPTOR.message_types_by_name['MessageOne'] = _MESSAGEONE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageOne = _reflection.GeneratedProtocolMessageType('MessageOne', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGEONE,
  __module__ = 'path3.path4.demo_pb2'
  # @@protoc_insertion_point(class_scope:path3.MessageOne)
  ))
_sym_db.RegisterMessage(MessageOne)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.github.biolee.path3.path4Z0github.com/biolee/grpc_starter/path3/path4;path4'))
# @@protoc_insertion_point(module_scope)
