// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: path1/path2/demo.proto

package com.github.biolee.path1.path2;

public final class Demo {
  private Demo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DemoReqOrBuilder extends
      // @@protoc_insertion_point(interface_extends:path1.path2.DemoReq)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    boolean hasMessageOne();
    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    com.github.biolee.path3.path4.Demo.MessageOne getMessageOne();
    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    com.github.biolee.path3.path4.Demo.MessageOneOrBuilder getMessageOneOrBuilder();
  }
  /**
   * Protobuf type {@code path1.path2.DemoReq}
   */
  public  static final class DemoReq extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:path1.path2.DemoReq)
      DemoReqOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoReq.newBuilder() to construct.
    private DemoReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoReq() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoReq(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.github.biolee.path3.path4.Demo.MessageOne.Builder subBuilder = null;
              if (messageOne_ != null) {
                subBuilder = messageOne_.toBuilder();
              }
              messageOne_ = input.readMessage(com.github.biolee.path3.path4.Demo.MessageOne.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageOne_);
                messageOne_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.biolee.path1.path2.Demo.DemoReq.class, com.github.biolee.path1.path2.Demo.DemoReq.Builder.class);
    }

    public static final int MESSAGE_ONE_FIELD_NUMBER = 1;
    private com.github.biolee.path3.path4.Demo.MessageOne messageOne_;
    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    public boolean hasMessageOne() {
      return messageOne_ != null;
    }
    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    public com.github.biolee.path3.path4.Demo.MessageOne getMessageOne() {
      return messageOne_ == null ? com.github.biolee.path3.path4.Demo.MessageOne.getDefaultInstance() : messageOne_;
    }
    /**
     * <code>.path3.MessageOne message_one = 1;</code>
     */
    public com.github.biolee.path3.path4.Demo.MessageOneOrBuilder getMessageOneOrBuilder() {
      return getMessageOne();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageOne_ != null) {
        output.writeMessage(1, getMessageOne());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageOne_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMessageOne());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.biolee.path1.path2.Demo.DemoReq)) {
        return super.equals(obj);
      }
      com.github.biolee.path1.path2.Demo.DemoReq other = (com.github.biolee.path1.path2.Demo.DemoReq) obj;

      boolean result = true;
      result = result && (hasMessageOne() == other.hasMessageOne());
      if (hasMessageOne()) {
        result = result && getMessageOne()
            .equals(other.getMessageOne());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageOne()) {
        hash = (37 * hash) + MESSAGE_ONE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageOne().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoReq parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.biolee.path1.path2.Demo.DemoReq prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code path1.path2.DemoReq}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:path1.path2.DemoReq)
        com.github.biolee.path1.path2.Demo.DemoReqOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoReq_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoReq_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.biolee.path1.path2.Demo.DemoReq.class, com.github.biolee.path1.path2.Demo.DemoReq.Builder.class);
      }

      // Construct using com.github.biolee.path1.path2.Demo.DemoReq.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (messageOneBuilder_ == null) {
          messageOne_ = null;
        } else {
          messageOne_ = null;
          messageOneBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoReq_descriptor;
      }

      public com.github.biolee.path1.path2.Demo.DemoReq getDefaultInstanceForType() {
        return com.github.biolee.path1.path2.Demo.DemoReq.getDefaultInstance();
      }

      public com.github.biolee.path1.path2.Demo.DemoReq build() {
        com.github.biolee.path1.path2.Demo.DemoReq result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.biolee.path1.path2.Demo.DemoReq buildPartial() {
        com.github.biolee.path1.path2.Demo.DemoReq result = new com.github.biolee.path1.path2.Demo.DemoReq(this);
        if (messageOneBuilder_ == null) {
          result.messageOne_ = messageOne_;
        } else {
          result.messageOne_ = messageOneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.biolee.path1.path2.Demo.DemoReq) {
          return mergeFrom((com.github.biolee.path1.path2.Demo.DemoReq)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.biolee.path1.path2.Demo.DemoReq other) {
        if (other == com.github.biolee.path1.path2.Demo.DemoReq.getDefaultInstance()) return this;
        if (other.hasMessageOne()) {
          mergeMessageOne(other.getMessageOne());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.biolee.path1.path2.Demo.DemoReq parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.biolee.path1.path2.Demo.DemoReq) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.github.biolee.path3.path4.Demo.MessageOne messageOne_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.biolee.path3.path4.Demo.MessageOne, com.github.biolee.path3.path4.Demo.MessageOne.Builder, com.github.biolee.path3.path4.Demo.MessageOneOrBuilder> messageOneBuilder_;
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public boolean hasMessageOne() {
        return messageOneBuilder_ != null || messageOne_ != null;
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public com.github.biolee.path3.path4.Demo.MessageOne getMessageOne() {
        if (messageOneBuilder_ == null) {
          return messageOne_ == null ? com.github.biolee.path3.path4.Demo.MessageOne.getDefaultInstance() : messageOne_;
        } else {
          return messageOneBuilder_.getMessage();
        }
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public Builder setMessageOne(com.github.biolee.path3.path4.Demo.MessageOne value) {
        if (messageOneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageOne_ = value;
          onChanged();
        } else {
          messageOneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public Builder setMessageOne(
          com.github.biolee.path3.path4.Demo.MessageOne.Builder builderForValue) {
        if (messageOneBuilder_ == null) {
          messageOne_ = builderForValue.build();
          onChanged();
        } else {
          messageOneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public Builder mergeMessageOne(com.github.biolee.path3.path4.Demo.MessageOne value) {
        if (messageOneBuilder_ == null) {
          if (messageOne_ != null) {
            messageOne_ =
              com.github.biolee.path3.path4.Demo.MessageOne.newBuilder(messageOne_).mergeFrom(value).buildPartial();
          } else {
            messageOne_ = value;
          }
          onChanged();
        } else {
          messageOneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public Builder clearMessageOne() {
        if (messageOneBuilder_ == null) {
          messageOne_ = null;
          onChanged();
        } else {
          messageOne_ = null;
          messageOneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public com.github.biolee.path3.path4.Demo.MessageOne.Builder getMessageOneBuilder() {
        
        onChanged();
        return getMessageOneFieldBuilder().getBuilder();
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      public com.github.biolee.path3.path4.Demo.MessageOneOrBuilder getMessageOneOrBuilder() {
        if (messageOneBuilder_ != null) {
          return messageOneBuilder_.getMessageOrBuilder();
        } else {
          return messageOne_ == null ?
              com.github.biolee.path3.path4.Demo.MessageOne.getDefaultInstance() : messageOne_;
        }
      }
      /**
       * <code>.path3.MessageOne message_one = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.biolee.path3.path4.Demo.MessageOne, com.github.biolee.path3.path4.Demo.MessageOne.Builder, com.github.biolee.path3.path4.Demo.MessageOneOrBuilder> 
          getMessageOneFieldBuilder() {
        if (messageOneBuilder_ == null) {
          messageOneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.biolee.path3.path4.Demo.MessageOne, com.github.biolee.path3.path4.Demo.MessageOne.Builder, com.github.biolee.path3.path4.Demo.MessageOneOrBuilder>(
                  getMessageOne(),
                  getParentForChildren(),
                  isClean());
          messageOne_ = null;
        }
        return messageOneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:path1.path2.DemoReq)
    }

    // @@protoc_insertion_point(class_scope:path1.path2.DemoReq)
    private static final com.github.biolee.path1.path2.Demo.DemoReq DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.biolee.path1.path2.Demo.DemoReq();
    }

    public static com.github.biolee.path1.path2.Demo.DemoReq getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoReq>
        PARSER = new com.google.protobuf.AbstractParser<DemoReq>() {
      public DemoReq parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoReq(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoReq> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoReq> getParserForType() {
      return PARSER;
    }

    public com.github.biolee.path1.path2.Demo.DemoReq getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface DemoRespOrBuilder extends
      // @@protoc_insertion_point(interface_extends:path1.path2.DemoResp)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    boolean hasMessageOne();
    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    com.github.biolee.path1.path2.Lib.MessageTwo getMessageOne();
    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder getMessageOneOrBuilder();
  }
  /**
   * Protobuf type {@code path1.path2.DemoResp}
   */
  public  static final class DemoResp extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:path1.path2.DemoResp)
      DemoRespOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DemoResp.newBuilder() to construct.
    private DemoResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DemoResp() {
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DemoResp(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.github.biolee.path1.path2.Lib.MessageTwo.Builder subBuilder = null;
              if (messageOne_ != null) {
                subBuilder = messageOne_.toBuilder();
              }
              messageOne_ = input.readMessage(com.github.biolee.path1.path2.Lib.MessageTwo.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(messageOne_);
                messageOne_ = subBuilder.buildPartial();
              }

              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.github.biolee.path1.path2.Demo.DemoResp.class, com.github.biolee.path1.path2.Demo.DemoResp.Builder.class);
    }

    public static final int MESSAGE_ONE_FIELD_NUMBER = 1;
    private com.github.biolee.path1.path2.Lib.MessageTwo messageOne_;
    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    public boolean hasMessageOne() {
      return messageOne_ != null;
    }
    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    public com.github.biolee.path1.path2.Lib.MessageTwo getMessageOne() {
      return messageOne_ == null ? com.github.biolee.path1.path2.Lib.MessageTwo.getDefaultInstance() : messageOne_;
    }
    /**
     * <code>.path1.MessageTwo message_one = 1;</code>
     */
    public com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder getMessageOneOrBuilder() {
      return getMessageOne();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (messageOne_ != null) {
        output.writeMessage(1, getMessageOne());
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (messageOne_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getMessageOne());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.github.biolee.path1.path2.Demo.DemoResp)) {
        return super.equals(obj);
      }
      com.github.biolee.path1.path2.Demo.DemoResp other = (com.github.biolee.path1.path2.Demo.DemoResp) obj;

      boolean result = true;
      result = result && (hasMessageOne() == other.hasMessageOne());
      if (hasMessageOne()) {
        result = result && getMessageOne()
            .equals(other.getMessageOne());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasMessageOne()) {
        hash = (37 * hash) + MESSAGE_ONE_FIELD_NUMBER;
        hash = (53 * hash) + getMessageOne().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.github.biolee.path1.path2.Demo.DemoResp parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.github.biolee.path1.path2.Demo.DemoResp prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code path1.path2.DemoResp}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:path1.path2.DemoResp)
        com.github.biolee.path1.path2.Demo.DemoRespOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoResp_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoResp_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.github.biolee.path1.path2.Demo.DemoResp.class, com.github.biolee.path1.path2.Demo.DemoResp.Builder.class);
      }

      // Construct using com.github.biolee.path1.path2.Demo.DemoResp.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        if (messageOneBuilder_ == null) {
          messageOne_ = null;
        } else {
          messageOne_ = null;
          messageOneBuilder_ = null;
        }
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.github.biolee.path1.path2.Demo.internal_static_path1_path2_DemoResp_descriptor;
      }

      public com.github.biolee.path1.path2.Demo.DemoResp getDefaultInstanceForType() {
        return com.github.biolee.path1.path2.Demo.DemoResp.getDefaultInstance();
      }

      public com.github.biolee.path1.path2.Demo.DemoResp build() {
        com.github.biolee.path1.path2.Demo.DemoResp result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.github.biolee.path1.path2.Demo.DemoResp buildPartial() {
        com.github.biolee.path1.path2.Demo.DemoResp result = new com.github.biolee.path1.path2.Demo.DemoResp(this);
        if (messageOneBuilder_ == null) {
          result.messageOne_ = messageOne_;
        } else {
          result.messageOne_ = messageOneBuilder_.build();
        }
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.github.biolee.path1.path2.Demo.DemoResp) {
          return mergeFrom((com.github.biolee.path1.path2.Demo.DemoResp)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.github.biolee.path1.path2.Demo.DemoResp other) {
        if (other == com.github.biolee.path1.path2.Demo.DemoResp.getDefaultInstance()) return this;
        if (other.hasMessageOne()) {
          mergeMessageOne(other.getMessageOne());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.github.biolee.path1.path2.Demo.DemoResp parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.github.biolee.path1.path2.Demo.DemoResp) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private com.github.biolee.path1.path2.Lib.MessageTwo messageOne_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.biolee.path1.path2.Lib.MessageTwo, com.github.biolee.path1.path2.Lib.MessageTwo.Builder, com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder> messageOneBuilder_;
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public boolean hasMessageOne() {
        return messageOneBuilder_ != null || messageOne_ != null;
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public com.github.biolee.path1.path2.Lib.MessageTwo getMessageOne() {
        if (messageOneBuilder_ == null) {
          return messageOne_ == null ? com.github.biolee.path1.path2.Lib.MessageTwo.getDefaultInstance() : messageOne_;
        } else {
          return messageOneBuilder_.getMessage();
        }
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public Builder setMessageOne(com.github.biolee.path1.path2.Lib.MessageTwo value) {
        if (messageOneBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          messageOne_ = value;
          onChanged();
        } else {
          messageOneBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public Builder setMessageOne(
          com.github.biolee.path1.path2.Lib.MessageTwo.Builder builderForValue) {
        if (messageOneBuilder_ == null) {
          messageOne_ = builderForValue.build();
          onChanged();
        } else {
          messageOneBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public Builder mergeMessageOne(com.github.biolee.path1.path2.Lib.MessageTwo value) {
        if (messageOneBuilder_ == null) {
          if (messageOne_ != null) {
            messageOne_ =
              com.github.biolee.path1.path2.Lib.MessageTwo.newBuilder(messageOne_).mergeFrom(value).buildPartial();
          } else {
            messageOne_ = value;
          }
          onChanged();
        } else {
          messageOneBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public Builder clearMessageOne() {
        if (messageOneBuilder_ == null) {
          messageOne_ = null;
          onChanged();
        } else {
          messageOne_ = null;
          messageOneBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public com.github.biolee.path1.path2.Lib.MessageTwo.Builder getMessageOneBuilder() {
        
        onChanged();
        return getMessageOneFieldBuilder().getBuilder();
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      public com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder getMessageOneOrBuilder() {
        if (messageOneBuilder_ != null) {
          return messageOneBuilder_.getMessageOrBuilder();
        } else {
          return messageOne_ == null ?
              com.github.biolee.path1.path2.Lib.MessageTwo.getDefaultInstance() : messageOne_;
        }
      }
      /**
       * <code>.path1.MessageTwo message_one = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.github.biolee.path1.path2.Lib.MessageTwo, com.github.biolee.path1.path2.Lib.MessageTwo.Builder, com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder> 
          getMessageOneFieldBuilder() {
        if (messageOneBuilder_ == null) {
          messageOneBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.github.biolee.path1.path2.Lib.MessageTwo, com.github.biolee.path1.path2.Lib.MessageTwo.Builder, com.github.biolee.path1.path2.Lib.MessageTwoOrBuilder>(
                  getMessageOne(),
                  getParentForChildren(),
                  isClean());
          messageOne_ = null;
        }
        return messageOneBuilder_;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:path1.path2.DemoResp)
    }

    // @@protoc_insertion_point(class_scope:path1.path2.DemoResp)
    private static final com.github.biolee.path1.path2.Demo.DemoResp DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.github.biolee.path1.path2.Demo.DemoResp();
    }

    public static com.github.biolee.path1.path2.Demo.DemoResp getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DemoResp>
        PARSER = new com.google.protobuf.AbstractParser<DemoResp>() {
      public DemoResp parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
          return new DemoResp(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DemoResp> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DemoResp> getParserForType() {
      return PARSER;
    }

    public com.github.biolee.path1.path2.Demo.DemoResp getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_path1_path2_DemoReq_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_path1_path2_DemoReq_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_path1_path2_DemoResp_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_path1_path2_DemoResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\026path1/path2/demo.proto\022\013path1.path2\032\026p" +
      "ath3/path4/demo.proto\032\025path1/path2/lib.p" +
      "roto\"1\n\007DemoReq\022&\n\013message_one\030\001 \001(\0132\021.p" +
      "ath3.MessageOne\"2\n\010DemoResp\022&\n\013message_o" +
      "ne\030\001 \001(\0132\021.path1.MessageTwo2B\n\013DemoServi" +
      "ce\0223\n\004Demo\022\024.path1.path2.DemoReq\032\025.path1" +
      ".path2.DemoRespBQ\n\035com.github.biolee.pat" +
      "h1.path2Z0github.com/biolee/grpc_starter" +
      "/path1/path2;path2b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.github.biolee.path3.path4.Demo.getDescriptor(),
          com.github.biolee.path1.path2.Lib.getDescriptor(),
        }, assigner);
    internal_static_path1_path2_DemoReq_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_path1_path2_DemoReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_path1_path2_DemoReq_descriptor,
        new java.lang.String[] { "MessageOne", });
    internal_static_path1_path2_DemoResp_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_path1_path2_DemoResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_path1_path2_DemoResp_descriptor,
        new java.lang.String[] { "MessageOne", });
    com.github.biolee.path3.path4.Demo.getDescriptor();
    com.github.biolee.path1.path2.Lib.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
