// Code generated by protoc-gen-go. DO NOT EDIT.
// source: path1/path2/demo.proto

/*
Package path2 is a generated protocol buffer package.

It is generated from these files:
	path1/path2/demo.proto
	path1/path2/lib.proto

It has these top-level messages:
	DemoReq
	DemoResp
	MessageTwo
*/
package path2

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import path3 "github.com/biolee/grpc_starter/path3/path4"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type DemoReq struct {
	MessageOne *path3.MessageOne `protobuf:"bytes,1,opt,name=message_one,json=messageOne" json:"message_one,omitempty"`
}

func (m *DemoReq) Reset()                    { *m = DemoReq{} }
func (m *DemoReq) String() string            { return proto.CompactTextString(m) }
func (*DemoReq) ProtoMessage()               {}
func (*DemoReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *DemoReq) GetMessageOne() *path3.MessageOne {
	if m != nil {
		return m.MessageOne
	}
	return nil
}

type DemoResp struct {
	MessageOne *MessageTwo `protobuf:"bytes,1,opt,name=message_one,json=messageOne" json:"message_one,omitempty"`
}

func (m *DemoResp) Reset()                    { *m = DemoResp{} }
func (m *DemoResp) String() string            { return proto.CompactTextString(m) }
func (*DemoResp) ProtoMessage()               {}
func (*DemoResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *DemoResp) GetMessageOne() *MessageTwo {
	if m != nil {
		return m.MessageOne
	}
	return nil
}

func init() {
	proto.RegisterType((*DemoReq)(nil), "path1.path2.DemoReq")
	proto.RegisterType((*DemoResp)(nil), "path1.path2.DemoResp")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for DemoService service

type DemoServiceClient interface {
	Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoResp, error)
}

type demoServiceClient struct {
	cc *grpc.ClientConn
}

func NewDemoServiceClient(cc *grpc.ClientConn) DemoServiceClient {
	return &demoServiceClient{cc}
}

func (c *demoServiceClient) Demo(ctx context.Context, in *DemoReq, opts ...grpc.CallOption) (*DemoResp, error) {
	out := new(DemoResp)
	err := grpc.Invoke(ctx, "/path1.path2.DemoService/Demo", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for DemoService service

type DemoServiceServer interface {
	Demo(context.Context, *DemoReq) (*DemoResp, error)
}

func RegisterDemoServiceServer(s *grpc.Server, srv DemoServiceServer) {
	s.RegisterService(&_DemoService_serviceDesc, srv)
}

func _DemoService_Demo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DemoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemoServiceServer).Demo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/path1.path2.DemoService/Demo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemoServiceServer).Demo(ctx, req.(*DemoReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _DemoService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "path1.path2.DemoService",
	HandlerType: (*DemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Demo",
			Handler:    _DemoService_Demo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "path1/path2/demo.proto",
}

func init() { proto.RegisterFile("path1/path2/demo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 227 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x90, 0x31, 0x4b, 0x43, 0x31,
	0x14, 0x85, 0x29, 0x88, 0xca, 0xcd, 0x64, 0xb0, 0x22, 0x0f, 0x04, 0xe9, 0xe4, 0x94, 0xd8, 0xc4,
	0x4d, 0x74, 0x28, 0xae, 0x22, 0x56, 0x27, 0x97, 0xf2, 0x12, 0x2f, 0xaf, 0x81, 0xa6, 0x37, 0x26,
	0x51, 0xff, 0xbe, 0xbc, 0xa4, 0x4a, 0x06, 0xe9, 0x72, 0x49, 0xce, 0x39, 0x5f, 0xc8, 0x3d, 0x70,
	0x16, 0xfa, 0xbc, 0x9e, 0xcb, 0x71, 0x2a, 0xf9, 0x8e, 0x9e, 0x44, 0x88, 0x94, 0x89, 0xb3, 0xa2,
	0x8b, 0xa2, 0x77, 0x25, 0xa4, 0x4b, 0xe8, 0xa6, 0x09, 0x75, 0xd3, 0x16, 0xde, 0x38, 0x53, 0xe5,
	0xd9, 0x1d, 0x1c, 0x3d, 0xa0, 0xa7, 0x25, 0x7e, 0x70, 0x05, 0xcc, 0x63, 0x4a, 0xfd, 0x80, 0x2b,
	0xda, 0xe2, 0xf9, 0xe4, 0x72, 0x72, 0xc5, 0xd4, 0x49, 0x79, 0x56, 0x8b, 0xc7, 0xea, 0x3c, 0x6d,
	0x71, 0x09, 0xfe, 0xef, 0x3c, 0xbb, 0x87, 0xe3, 0x8a, 0xa7, 0xb0, 0x8f, 0x9f, 0xff, 0xf2, 0xaf,
	0xdf, 0xd4, 0xf2, 0x6a, 0x01, 0x6c, 0xe4, 0x5f, 0x30, 0x7e, 0x39, 0x8b, 0x5c, 0xc3, 0xc1, 0x78,
	0xe5, 0xa7, 0xa2, 0x59, 0x49, 0xec, 0x3e, 0xd8, 0x4d, 0xff, 0x51, 0x53, 0x58, 0x3c, 0xc3, 0x85,
	0x25, 0x2f, 0x06, 0x97, 0xd7, 0x9f, 0x46, 0x18, 0x47, 0x1b, 0xc4, 0x36, 0xf9, 0x76, 0xbd, 0xb3,
	0x2c, 0x79, 0x59, 0x6d, 0x39, 0xc4, 0x60, 0x57, 0x29, 0xf7, 0x31, 0x63, 0x94, 0x4d, 0x33, 0xb7,
	0x65, 0x9a, 0xc3, 0x52, 0x8e, 0xfe, 0x09, 0x00, 0x00, 0xff, 0xff, 0x70, 0x0f, 0x84, 0x99, 0x72,
	0x01, 0x00, 0x00,
}
