# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path1/path2/demo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from path3.path4 import demo_pb2 as path3_dot_path4_dot_demo__pb2
from path1.path2 import lib_pb2 as path1_dot_path2_dot_lib__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='path1/path2/demo.proto',
  package='path1.path2',
  syntax='proto3',
  serialized_pb=_b('\n\x16path1/path2/demo.proto\x12\x0bpath1.path2\x1a\x16path3/path4/demo.proto\x1a\x15path1/path2/lib.proto\"7\n\x07\x44\x65moReq\x12,\n\x0bmessage_one\x18\x01 \x01(\x0b\x32\x17.path3.path4.MessageOne\"8\n\x08\x44\x65moResp\x12,\n\x0bmessage_one\x18\x01 \x01(\x0b\x32\x17.path1.path2.MessageTwo2B\n\x0b\x44\x65moService\x12\x33\n\x04\x44\x65mo\x12\x14.path1.path2.DemoReq\x1a\x15.path1.path2.DemoRespBQ\n\x1d\x63om.github.biolee.path1.path2Z0github.com/biolee/grpc_starter/path1/path2;path2b\x06proto3')
  ,
  dependencies=[path3_dot_path4_dot_demo__pb2.DESCRIPTOR,path1_dot_path2_dot_lib__pb2.DESCRIPTOR,])




_DEMOREQ = _descriptor.Descriptor(
  name='DemoReq',
  full_name='path1.path2.DemoReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_one', full_name='path1.path2.DemoReq.message_one', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=86,
  serialized_end=141,
)


_DEMORESP = _descriptor.Descriptor(
  name='DemoResp',
  full_name='path1.path2.DemoResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='message_one', full_name='path1.path2.DemoResp.message_one', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=143,
  serialized_end=199,
)

_DEMOREQ.fields_by_name['message_one'].message_type = path3_dot_path4_dot_demo__pb2._MESSAGEONE
_DEMORESP.fields_by_name['message_one'].message_type = path1_dot_path2_dot_lib__pb2._MESSAGETWO
DESCRIPTOR.message_types_by_name['DemoReq'] = _DEMOREQ
DESCRIPTOR.message_types_by_name['DemoResp'] = _DEMORESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DemoReq = _reflection.GeneratedProtocolMessageType('DemoReq', (_message.Message,), dict(
  DESCRIPTOR = _DEMOREQ,
  __module__ = 'path1.path2.demo_pb2'
  # @@protoc_insertion_point(class_scope:path1.path2.DemoReq)
  ))
_sym_db.RegisterMessage(DemoReq)

DemoResp = _reflection.GeneratedProtocolMessageType('DemoResp', (_message.Message,), dict(
  DESCRIPTOR = _DEMORESP,
  __module__ = 'path1.path2.demo_pb2'
  # @@protoc_insertion_point(class_scope:path1.path2.DemoResp)
  ))
_sym_db.RegisterMessage(DemoResp)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.github.biolee.path1.path2Z0github.com/biolee/grpc_starter/path1/path2;path2'))

_DEMOSERVICE = _descriptor.ServiceDescriptor(
  name='DemoService',
  full_name='path1.path2.DemoService',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=201,
  serialized_end=267,
  methods=[
  _descriptor.MethodDescriptor(
    name='Demo',
    full_name='path1.path2.DemoService.Demo',
    index=0,
    containing_service=None,
    input_type=_DEMOREQ,
    output_type=_DEMORESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEMOSERVICE)

DESCRIPTOR.services_by_name['DemoService'] = _DEMOSERVICE

# @@protoc_insertion_point(module_scope)
