/**
 * @fileoverview
 * @enhanceable
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var path3_path4_demo_pb = require('../../path3/path4/demo_pb.js');
var path1_path2_lib_pb = require('../../path1/path2/lib_pb.js');
goog.exportSymbol('proto.path1.path2.DemoReq', null, global);
goog.exportSymbol('proto.path1.path2.DemoResp', null, global);

/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path1.path2.DemoReq = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path1.path2.DemoReq, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.path1.path2.DemoReq.displayName = 'proto.path1.path2.DemoReq';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path1.path2.DemoReq.prototype.toObject = function(opt_includeInstance) {
  return proto.path1.path2.DemoReq.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path1.path2.DemoReq} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path1.path2.DemoReq.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageOne: (f = msg.getMessageOne()) && path3_path4_demo_pb.MessageOne.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path1.path2.DemoReq}
 */
proto.path1.path2.DemoReq.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path1.path2.DemoReq;
  return proto.path1.path2.DemoReq.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path1.path2.DemoReq} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path1.path2.DemoReq}
 */
proto.path1.path2.DemoReq.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new path3_path4_demo_pb.MessageOne;
      reader.readMessage(value,path3_path4_demo_pb.MessageOne.deserializeBinaryFromReader);
      msg.setMessageOne(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path1.path2.DemoReq.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path1.path2.DemoReq.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path1.path2.DemoReq} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path1.path2.DemoReq.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageOne();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      path3_path4_demo_pb.MessageOne.serializeBinaryToWriter
    );
  }
};


/**
 * optional path3.path4.MessageOne message_one = 1;
 * @return {?proto.path3.path4.MessageOne}
 */
proto.path1.path2.DemoReq.prototype.getMessageOne = function() {
  return /** @type{?proto.path3.path4.MessageOne} */ (
    jspb.Message.getWrapperField(this, path3_path4_demo_pb.MessageOne, 1));
};


/** @param {?proto.path3.path4.MessageOne|undefined} value */
proto.path1.path2.DemoReq.prototype.setMessageOne = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.path1.path2.DemoReq.prototype.clearMessageOne = function() {
  this.setMessageOne(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.path1.path2.DemoReq.prototype.hasMessageOne = function() {
  return jspb.Message.getField(this, 1) != null;
};



/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.path1.path2.DemoResp = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.path1.path2.DemoResp, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  proto.path1.path2.DemoResp.displayName = 'proto.path1.path2.DemoResp';
}


if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto suitable for use in Soy templates.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     com.google.apps.jspb.JsClassTemplate.JS_RESERVED_WORDS.
 * @param {boolean=} opt_includeInstance Whether to include the JSPB instance
 *     for transitional soy proto support: http://goto/soy-param-migration
 * @return {!Object}
 */
proto.path1.path2.DemoResp.prototype.toObject = function(opt_includeInstance) {
  return proto.path1.path2.DemoResp.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Whether to include the JSPB
 *     instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.path1.path2.DemoResp} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path1.path2.DemoResp.toObject = function(includeInstance, msg) {
  var f, obj = {
    messageOne: (f = msg.getMessageOne()) && path1_path2_lib_pb.MessageTwo.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.path1.path2.DemoResp}
 */
proto.path1.path2.DemoResp.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.path1.path2.DemoResp;
  return proto.path1.path2.DemoResp.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.path1.path2.DemoResp} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.path1.path2.DemoResp}
 */
proto.path1.path2.DemoResp.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new path1_path2_lib_pb.MessageTwo;
      reader.readMessage(value,path1_path2_lib_pb.MessageTwo.deserializeBinaryFromReader);
      msg.setMessageOne(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.path1.path2.DemoResp.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.path1.path2.DemoResp.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.path1.path2.DemoResp} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.path1.path2.DemoResp.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMessageOne();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      path1_path2_lib_pb.MessageTwo.serializeBinaryToWriter
    );
  }
};


/**
 * optional MessageTwo message_one = 1;
 * @return {?proto.path1.path2.MessageTwo}
 */
proto.path1.path2.DemoResp.prototype.getMessageOne = function() {
  return /** @type{?proto.path1.path2.MessageTwo} */ (
    jspb.Message.getWrapperField(this, path1_path2_lib_pb.MessageTwo, 1));
};


/** @param {?proto.path1.path2.MessageTwo|undefined} value */
proto.path1.path2.DemoResp.prototype.setMessageOne = function(value) {
  jspb.Message.setWrapperField(this, 1, value);
};


proto.path1.path2.DemoResp.prototype.clearMessageOne = function() {
  this.setMessageOne(undefined);
};


/**
 * Returns whether this field is set.
 * @return {!boolean}
 */
proto.path1.path2.DemoResp.prototype.hasMessageOne = function() {
  return jspb.Message.getField(this, 1) != null;
};


goog.object.extend(exports, proto.path1.path2);
