# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from path1.path2 import demo_pb2 as path1_dot_path2_dot_demo__pb2


class DemoServiceStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.Demo = channel.unary_unary(
        '/path1.path2.DemoService/Demo',
        request_serializer=path1_dot_path2_dot_demo__pb2.DemoReq.SerializeToString,
        response_deserializer=path1_dot_path2_dot_demo__pb2.DemoResp.FromString,
        )


class DemoServiceServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def Demo(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_DemoServiceServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'Demo': grpc.unary_unary_rpc_method_handler(
          servicer.Demo,
          request_deserializer=path1_dot_path2_dot_demo__pb2.DemoReq.FromString,
          response_serializer=path1_dot_path2_dot_demo__pb2.DemoResp.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'path1.path2.DemoService', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
