# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: path1/path2/lib.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='path1/path2/lib.proto',
  package='path1',
  syntax='proto3',
  serialized_pb=_b('\n\x15path1/path2/lib.proto\x12\x05path1\"\x1a\n\nMessageTwo\x12\x0c\n\x04name\x18\x01 \x01(\tBQ\n\x1d\x63om.github.biolee.path1.path2Z0github.com/biolee/grpc_starter/path1/path2;path2b\x06proto3')
)




_MESSAGETWO = _descriptor.Descriptor(
  name='MessageTwo',
  full_name='path1.MessageTwo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='path1.MessageTwo.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=58,
)

DESCRIPTOR.message_types_by_name['MessageTwo'] = _MESSAGETWO
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MessageTwo = _reflection.GeneratedProtocolMessageType('MessageTwo', (_message.Message,), dict(
  DESCRIPTOR = _MESSAGETWO,
  __module__ = 'path1.path2.lib_pb2'
  # @@protoc_insertion_point(class_scope:path1.MessageTwo)
  ))
_sym_db.RegisterMessage(MessageTwo)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('\n\035com.github.biolee.path1.path2Z0github.com/biolee/grpc_starter/path1/path2;path2'))
# @@protoc_insertion_point(module_scope)
